---
- name: Provision all
  hosts: all
  become: yes
  tasks:
  - name: Update apt's repository indices
    apt:
      cache_valid_time: 3600  # ..seconds = 1 hour
    when: ansible_distribution in ['Ubuntu', 'Debian']

- name: Yet another provisioning example
  hosts: my-ubuntu
  gather_facts: no
  tasks:
  - name: Greet
    debug: msg="Hello, World!"