---
- name: Perform full upgrade
  hosts: dev-java
  gather_facts: no
  become: yes
  tasks:
  - name: Do upgrade
    apt:
      update_cache: yes
      upgrade: dist
    register: upgrade
  # https://github.com/ansible/ansible/issues/26521#issuecomment-371142617
  - name: Remove nondownloadable packages from cache
    apt:
      autoclean: yes
    when: upgrade is succeeded
  - name: Remove and purge orphaned packages
    apt:
      autoremove: yes
      purge: yes
    when: upgrade is succeeded

- name: Install Gradle
  hosts: dev-java
  gather_facts: no
  become: yes
  tasks:
  # https://askubuntu.com/a/975018
  - name: Add repository
    apt_repository: repo=ppa:cwchien/gradle
  - name: Add package
    apt: name=gradle

- name: Install Oracle JDK 9
  hosts: dev-java
  gather_facts: no
  become: yes
  tasks:
  # IntelliJ can not use OpenJDK. So, install Oracle.
  # https://stackoverflow.com/questions/47296429
  - name: Add repository
    apt_repository: repo=ppa:webupd8team/java
  # https://stackoverflow.com/a/26591300
  - name: Blindly accept Oracle's license
    debconf:
      name: oracle-java9-installer
      question: shared/accepted-oracle-license-v1-1
      value: "true"
      vtype: select
  - name: Add package
    apt: name=oracle-java9-installer

- name: Figure out which snaps are installed
  hosts: dev-java
  gather_facts: no
  become: yes
  tasks:
  - name: Install Snap, if missing
    apt: name=snap
  - name: Read list
    command: snap list
    register: snaps

- name: Install GitKraken
  hosts: dev-java
  gather_facts: no
  become: yes
  tasks:
  - command: snap install gitkraken
    when: "'gitkraken' not in snaps.stdout"

- name: Install IntelliJ IDEA
  hosts: dev-java
  gather_facts: no
  become: yes
  tasks:
  - command: snap install intellij-idea-community --classic --edge
    when: "'intellij-idea-community' not in snaps.stdout"

- name: Install Visual Studio Code
  hosts: dev-java
  gather_facts: no
  become: yes
  tasks:
  - command: snap install vscode --classic
    when: "'vscode' not in snaps.stdout"